### ISSUE TITLE
Office_macro processor error on file with no extension.

### ISSUE THREAD

**Issue by jarrodcoulter** [certsocietegenerale/fame#10]
In testing FAME when unzipped files do not have an extension attached, just the MD5 as the filename. FAME does detect the correct file type through strings or the file command and reports that data in the UI. But, the office_macros module errors on a word document. I'm assuming the error is due to no file extension attached to the file. The file does not have macros, so I guess I would expect the results to indicate that.

Example file: https://www.virustotal.com/en/file/ef9495d4d279e595083a92d044561da1f7c48f8885e98eab2bc745e48cb93028/analysis/, but when you download it, rename to the md5hash with no extension.

Steps to Reproduce
Upload a word document file with no extension inside a zip file.

Expected behavior
Either a message is returned that the document does not contain macros, or appending the extension to the file based on other static data information at processing time.

Actual behavior
The office_macros module errors out and I do not get the macros for further analysis.

Debug
2017-03-28 10:25: debug: Trying to run office_macros
2017-03-28 10:25: error: office_macros: Could not run on /home/disdude/fame/storage/<storage_loc>/a4aac4740b67cdf90f1068353376d28d.
 Traceback (most recent call last):
  File "/home/disdude/fame/fame/core/module.py", line 471, in _try_each
    return self.each_with_type(target, file_type)
  File "/home/disdude/fame/fame/core/module.py", line 430, in each_with_type
    return self.each(target)
  File "/home/disdude/fame/fame/modules/community/processing/office_macros/office_macros.py", line 45, in each
    analysis = sorted(analysis, key=lambda type_decoded_encoded: len(type_decoded_encoded[2]), reverse=True)
TypeError: 'NoneType' object is not iterable

2017-03-28 10:25: debug: Done with office_macros

**Comment by gaelmuller** [comment]
This was fixed in https://github.com/certsocietegenerale/fame_modules/commit/be1645d1b703f1a039b028163ba00145b7b263a1.

You can update the community modules directly from the web UI.
