### ISSUE TITLE
nginx not serving pictures of FAME after fresh install?!

### ISSUE THREAD

**Issue by littlAcen** [certsocietegenerale/fame#147]
### Description
look above ;)

### Steps to Reproduce
i did a fresh install

#### Expected behavior
seeing pictures

#### Actual behavior
just seeing text no pictures (background and so forth)

### Debug
[Include the output of ``utils/run.sh utils/troubleshoot.py``]

**Comment by Augustin-FL** [comment]
hi,

Could you please give me more context about your the issue? what is the error being displayed on nginx logs when loading the page? (they are located at `/var/log/nginx/error.log`)

Could you also confirm that you have changed `/REPLACE/WITH/YOUR/PATH/` in your nginx configuration?

```
    location /static/ {
      alias /REPLACE/WITH/YOUR/PATH/fame/web/static/;
    }
}
```

**Comment by Augustin-FL** [comment]
I will close this issue, since it look like a misconfiguration on your side more than a bug on FAME.
Feel free to reopen it if you still need help !
