### ISSUE TITLE
Docker : Python: error libcrypto.so.1.1

### ISSUE THREAD

**Issue by Yoanndp** [certsocietegenerale/fame#150]
### Description
I am encountering an issue while running Fame in a Docker container. The application fails with the following 

`fame_web | python: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory`

### Steps to Reproduce
1. Clone the repository
2. Create the fame.env file
3. Build the Docker image
4. Run the Docker container.
5. Observe the error mentioned above.

#### Expected behavior
I expect the application to run successfully inside the Docker container without any shared library errors.

#### Actual behavior
The application fails to start inside the Docker container and throws a libcrypto.so.1.1 shared library error.

**Comment by Augustin-FL** [comment]
Hi
I tried to replicate this issue but I don't arrive to. I must be missing something.

Could you confirm if your container is using python 3.11.2 on Debian 12.2? does `python3 -c "print('test')"` work on the container ?
Also, did you enable/use any module before having this issue ?

Fyi, the container is indeed using `libcrypto.so.3` (`libcrypto.so.1.1` is deprecated), but this doesn't seem to be an issue ?

**Comment by Augustin-FL** [comment]
Thank you for these inputs

Could you please execute the following commands and tell me if they work?

```
$ docker run -it --rm fame /bin/bash 
fame@b11ee4d7593f:/opt$ python3 -c "print('test')"
test
fame@b11ee4d7593f:/opt$ fame/utils/run.sh 
[+] Creating virtualenv... (or [+] Using existing virtualenv.)
[...]
fame@b11ee4d7593f:/opt$ source fame/env/bin/activate
(env) fame@b11ee4d7593f:/opt$ python3 -c "print('test')"
test
```

Also, could you tell me what Linux distribution are you using? (An issue with your host server is the last thing I would suspect in this kind of situation, but since it's working on my machine and not in yours...I would like to at least be able to replicate the issue)

**Comment by Augustin-FL** [comment]
Okay...Super strange :(

Could you try to run the docker with the volume and networks, and tell me if you are able to launch FAME web service manually?

```
$ docker run -it --rm -v docker_env:/opt/fame/env/ -v docker_modules:/opt/fame/fame/modules/ -v docker_storage:/opt/fame/storage/ -v docker_temp:/opt/fame/temp/ -v docker_avatars:/opt/fame/web/static/img/avatars/ --network $(docker network ls -f name=fame -q) fame /bin/bash 
fame@82d231416497:/opt$ cd fame/
fame@82d231416497:/opt$ utils/run.sh
[...]
fame@82d231416497:~$ source env/bin/activate
(env) fame@82d231416497:~$ python3 utils/install.py
[?] MongoDB host [localhost]: fame_db
[?] MongoDB port [27017]: 
[?] MongoDB database [fame]: 
[?] MongoDB username: user <- Taken from fame.env
[?] MongoDB password: pass <- taken from fame.env

Choose your installation type:

 - 1: Web server + local worker
 - 2: Remote worker

[?] Installation type [1]: 1
[+] performing local install
[?] FAME's URL for worker [http://localhost]: http://fame_web
[+] Creating configuration file ...
[+] Generating SSH key ...
[+] Creating initial data ...
[+] There are already users in the database.
[+] Community repository already installed.
(env) fame@82d231416497:~$ python3 webserver.py 
 * Serving Flask app 'webserver'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:4200
 * Running on http://172.20.0.3:4200
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 939-208-924
```

**Comment by Augustin-FL** [comment]
> I am using RHEL 8

I was able to run FAME with Podman 

I faced many difficulties (dnsname plugin not enabled by default, for instance...) but I still was not able to replicate your issue.

**Comment by Augustin-FL** [comment]
> It throws me the exact same issue with this command.

Does `fame@b11ee4d7593f:/opt$ python3 -c "print('test')"` works? Can you double-check if the python version is still 3.12.2 when the volume are mounted and the virtualenv is activated?

**Comment by Augustin-FL** [comment]
Execute `deactivate` to leave the virtualenv, then execute `python3 -c "print('test')"` again. Does it work this time?

If yes, then it means the issue comes from the virtualenv. Could you please try to rm -rf /opt/fame/env/* inside the container, then run again `utils/run.sh` to re-install the virtualenv ?

> Although Podman is installed, it's not being used there

I am quite circonspect about this. Could you confirm this using `docker --version` ? 

![image](https://github.com/certsocietegenerale/fame/assets/9406403/e06c1db8-feed-4f91-af0f-c9ee67d2354e)

**Comment by Augustin-FL** [comment]
Hum...
Well, I will close this issue, given it is likely docker-related (the `env` folder is a docker volume) and docker is not officially supported on RHEL.
