### ISSUE TITLE
Private vulnerability reporting 

### ISSUE THREAD

**Issue by Sim4n6** [certsocietegenerale/fame#159]
Could you please enable the private vulnerability reporting feature i' your github repository?

 Thank you @sim4n6

**Comment by Sim4n6** [comment]
For further details https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by certsocietegenerale** [comment]
Hello @Sim4n6 

Done

**Comment by Sim4n6** [comment]
I'm working on the report right away ... Appreciate your responsiveness.

**Comment by Sim4n6** [comment]
report sent.
