### ISSUE TITLE
Private vulnerability reporting

### ISSUE THREAD

**Issue by Sim4n6** [certsocietegenerale/fame#160]
Regarding issue #159, the report is sent here 
https://github.com/certsocietegenerale/fame/security/advisories/GHSA-9gw7-hxgx-f6rv

**Comment by Sim4n6** [comment]
Github notifications are silent by default on the mobile app for th private vulnerability reporting feature.

**Comment by certsocietegenerale** [comment]
Hello

We have seen the report and are currently assessing its validity. We will close this issue and answer on your report.
