### ISSUE TITLE
CVE ID assignment

### ISSUE THREAD

**Issue by Sim4n6** [certsocietegenerale/fame#161]
### Description
Regarding the advisory https://github.com/certsocietegenerale/fame/security/advisories/GHSA-9gw7-hxgx-f6rv could you please issue a CVE ID assignment in case yo are a CNA or request a CVE from within the advisory. 

### Steps to Reproduce

https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/publishing-a-repository-security-advisory#requesting-a-cve-identification-number-optional

#### Expected behavior
- assign a CVE ID 

#### Actual behavior
Nothing for now

**Comment by Augustin-FL** [comment]
Hello, 

As stated privately, we will not be providing a CVE for this Github Advisory. 

Github Issues are supposed to be for development related questions only. We will close this issue. 

Thank you for disclosing this vulnerability.

Regards,
CERT Société Générale

**Comment by certsocietegenerale** [comment]
Hello, 

As stated privately, we will not be providing a CVE for this Github Advisory. 

Github Issues are supposed to be for development related questions only. We will close this issue. 

Thank you for disclosing this vulnerability.

Regards,
CERT Société Générale
