### ISSUE TITLE
Docker SSH key mismatch

### ISSUE THREAD

**Issue by heck-gd** [certsocietegenerale/fame#164]
### Description
When running FAME under Docker, there is a mismatch between _key shown_ and _key used_ for private module pulling.

### Steps to Reproduce
1. Set up a fresh FAME instance using docker compose.
2. Add a private module, copying the displayed public key.
3. Note how authentication fails.

#### Expected behavior
The application uses the key it shows in web UI to authenticate to git.

#### Actual behavior
`fame_web` and `fame_updater` each generate an RSA key and don't share it, causing the user to wonder what could possibly have gone wrong.

**Comment by Augustin-FL** [comment]
Hi,

Indeed, this is why there is an variable `FAME_GIT_SSH_KEY` in [fame.env](https://github.com/certsocietegenerale/fame/blob/master/docker/fame.env.template#L10). You should set this variable if you plan to use private repositories on a dockerized FAME instance.

Thanks for reporting this issue, still: the UI and/or the documentation should be improved here.
