### ISSUE TITLE
Delete users

### ISSUE THREAD

**Issue by nebu10uz** [certsocietegenerale/fame#17]
### Feature Request
Capability to delete users from the fame portal.

**Comment by gaelmuller** [comment]
What would happen to analyses created by these users ?

Do we keep only their names and avatars ? Or display something like "Removed User" ?

**Comment by nebu10uz** [comment]
I see what you mean. 

It would be nice to have the option to remove the user and leave the analyses created and also have the option to remove the user and all data the user created. For example, if I create a Test User, I would like to test Fame and when completed, delete the user and all data.

Another feature that you can consider for the future is to have the option to delete individual analysis.
