### ISSUE TITLE
Internal Certificate Authority for Modules

### ISSUE THREAD

**Issue by mshelton** [certsocietegenerale/fame#20]
### Description
We use Yeti and FAME with TLS certificates from an internal Certificate Authority.  When using the Yeti Threat Intelligence Module, the Yeti module fails because Python requests cannot verify the certificate.  Short of not verifying TLS connections, is there a workaround where I can add my CA certificate to FAME?  

### Steps to Reproduce
Use a self-signed or internal CA-signed Yeti connection within FAME.

#### Expected behavior
The Yeti Module should work as expected

#### Actual behavior
I am getting the following error message:

2017-05-09 19:11: error: error in threat intelligence module 'Yeti': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

**Comment by gaelmuller** [comment]
You should be able to specify a list of trusted certificates using the `REQUESTS_CA_BUNDLEˋ.

See http://docs.python-requests.org/en/master/user/advanced/ for more details.

**Comment by mshelton** [comment]
Does the FAME worker process read environment variables?  I'll keep researching on my side but I was under the impression that it did not.

**Comment by gaelmuller** [comment]
Never tested, but I don't see why it would not.

Were you able to do what you wanted ?

**Comment by gaelmuller** [comment]
Closing this issue, do not hesitate to reopen if needed.
