### ISSUE TITLE
ThreatIntelligence Module Debugging

### ISSUE THREAD

**Issue by nbcmrg** [certsocietegenerale/fame#22]
I'm writing a TI module to enrich analysis using an internal data source. I implemented both "ioc_submission" and "ioc_lookup" methods. How can I test this now? Nothing in the interface shows up similar to the "Send to Yeti".  

It may be convenient to add a way to test TI modules like processing modules "single_module.py".

**Comment by gaelmuller** [comment]
I am adding the "feature_request" tag for the way to test TI modules similar to "single_module.py".

Where is your Python file ? It should be inside the "modules" directory. If it is, you need to hit "Reload" on the "Configuration" page for your module to be taken into account. It should then appear in the list of modules, where you will be able to enable it.

**Comment by nbcmrg** [comment]
Thanks! I identified the issue with my module. I was not explicitly returning True from the initialize method so the module never executed. My mistake. Thanks for your timely response.

**Comment by Heat-Miser** [comment]
Hello

I guess the problem has been solved thanks to @gaelmuller ! Can we close this issue ?

Thanks !
