### ISSUE TITLE
[+] Generating SSH key ... ImportError: No module named rfc6266

### ISSUE THREAD

**Issue by Daduke11** [certsocietegenerale/fame#24]
### Description
[+] Generating SSH key ... ImportError: No module named rfc6266
During fresh Installation of fame I've encountered the following error:
[+] Generating SSH key ...
Traceback (most recent call last):
  File "utils/install.py", line 227, in <module>
    main()
  File "utils/install.py", line 221, in main
    perform_local_installation(context)
  File "utils/install.py", line 143, in perform_local_installation
    from fame.core import fame_init
  File "/home/lacerator/fame/fame/core/__init__.py", line 2, in <module>
    from fame.core.module_dispatcher import dispatcher
  File "/home/lacerator/fame/fame/core/module_dispatcher.py", line 8, in <module>
    from fame.common.utils import get_class, iterify, unique_for_key
  File "/home/lacerator/fame/fame/common/utils.py", line 10, in <module>
    from rfc6266 import parse_requests_response
ImportError: No module named rfc6266

I have sudo pip install rfc6266 and still the same issue happens.

### Steps to Reproduce
I'm running inside a VM using VMware workstation 12
1) Install Ubuntu 16.04 LTS latest updates and build
2) Install MongoDB shell version v3.4.5
3) Install Fame

#### Expected behavior
[How are you expecting the application to behave?]
Fame to install without errors.

#### Actual behavior
[How is the application behaving? (include any stacktraces, logs, screenshots, etc.)]
[+] Generating SSH key ...
Traceback (most recent call last):
  File "utils/install.py", line 227, in <module>
    main()
  File "utils/install.py", line 221, in main
    perform_local_installation(context)
  File "utils/install.py", line 143, in perform_local_installation
    from fame.core import fame_init
  File "/home/lacerator/fame/fame/core/__init__.py", line 2, in <module>
    from fame.core.module_dispatcher import dispatcher
  File "/home/lacerator/fame/fame/core/module_dispatcher.py", line 8, in <module>
    from fame.common.utils import get_class, iterify, unique_for_key
  File "/home/lacerator/fame/fame/common/utils.py", line 10, in <module>
    from rfc6266 import parse_requests_response
ImportError: No module named rfc6266

### Debug
[Include the output of ``utils/run.sh utils/troubleshoot.py``]

utils/run.sh utils/troubleshoot.py
[+] Using existing virtualenv.

########## VERSION ##########

OS: Linux-4.4.0-66-generic-x86_64-with-Ubuntu-16.04-xenial
Python: 2.7.12

########## DEPENDENCIES ###########

alabaster==0.7.10
amqp==2.1.4
Babel==2.4.0
billiard==3.5.0.2
celery==4.0.2
certifi==2017.4.17
chardet==3.0.4
click==6.7
docutils==0.13.1
Flask==0.12.2
Flask-Classy==0.6.10
Flask-Login==0.3.2
Flask-Negotiation==0.1.9
flask-paginate==0.5.0
gitdb2==2.0.2
GitPython==2.1.5
idna==2.5
imagesize==0.7.1
itsdangerous==0.24
Jinja2==2.9.6
kombu==4.0.2
LEPL==5.1.3
markdown2==2.3.4
MarkupSafe==1.0
Pygments==2.2.0
pymongo==3.4.0
python-magic==0.4.13
pytz==2017.2
requests==2.18.1
-e git+https://github.com/g2p/rfc6266@cad58963ed13f5e1068fcc9e4326123b6b2bdcf8#egg=rfc6266
six==1.10.0
smmap2==2.0.3
snowballstemmer==1.2.1
Sphinx==1.6.2
sphinx-rtd-theme==0.2.4
sphinxcontrib-httpdomain==1.5.0
sphinxcontrib-websupport==1.0.1
typing==3.6.1
urllib3==1.21.1
vine==1.1.3
Werkzeug==0.12.2
zxcvbn==1.0

########## MongoDB ##########

Version: 3.4.5
Authorization check: True

########## Configuration ##########

Modules:

**Comment by gaelmuller** [comment]
This should be fixed by 3f6a690917eeea62c10d62f369996e918c19d767.

Could you rerun the installation script and confirm ?

**Comment by Daduke11** [comment]
Thanks! It works.
