### ISSUE TITLE
Russian symbols mess

### ISSUE THREAD

**Issue by rilian-la-te** [certsocietegenerale/fame#26]
### Description
If module returns Russian symbols in detailed results, we see a mess

### Steps to Reproduce
Write sample module, that will return string "фывапролдж"
#### Expected behavior
see "фывапролдж" in web interface

#### Actual behavior
Like this:
![scr](https://user-images.githubusercontent.com/1329638/28372221-c9e90824-6ca7-11e7-9fea-48a3e2b82086.png)

### Debug
fame@fame-server:~/fame$ utils/run.sh utils/troubleshoot.py
[+] Using existing virtualenv.

########## VERSION ##########

OS: Linux-4.4.0-83-generic-x86_64-with-Ubuntu-16.04-xenial
Python: 2.7.12

########## DEPENDENCIES ###########

alabaster==0.7.10
amqp==2.2.1
androguard==3.0.1
Babel==2.4.0
bamfdetect==1.6.13
beautifulsoup4==4.6.0
billiard==3.5.0.3
bs4==0.0.1
celery==4.0.2
certifi==2017.4.17
chardet==3.0.4
click==6.7
docutils==0.13.1
Flask==0.12.2
Flask-Classy==0.6.10
Flask-Login==0.3.2
Flask-Negotiation==0.1.9
flask-paginate==0.5.0
future==0.16.0
gitdb2==2.0.2
GitPython==2.1.5
googleplay-api==0.1.0
idna==2.5
ijson==2.3
imagesize==0.7.1
itsdangerous==0.24
Jinja2==2.9.6
kombu==4.0.2
LEPL==5.1.3
markdown2==2.3.4
MarkupSafe==1.0
oletools==0.51
pbkdf2==1.3
pefile==2016.3.28
pkg-resources==0.0.0
protobuf==3.3.0
pycrypto==2.6.1
pyelftools==0.24
Pygments==2.2.0
pymongo==3.4.0
python-magic==0.4.13
pytz==2017.2
rarfile==3.0
requests==2.18.1
rfc6266==0.0.4
six==1.10.0
smmap2==2.0.3
snowballstemmer==1.2.1
Sphinx==1.6.3
sphinx-rtd-theme==0.2.4
sphinxcontrib-httpdomain==1.5.0
sphinxcontrib-websupport==1.0.1
typing==3.6.1
urllib3==1.21.1
uWSGI==2.0.15
vine==1.1.4
volatility==2.6
Werkzeug==0.12.2
yara-python==3.6.3
zxcvbn==1.0

########## MongoDB ##########

Version: 3.4.6
Authorization check: True

########## Configuration ##########

types: True
virustotal: False
email: False
malware_config: False
volatility: True

Modules:

McAfee                    Antivirus            Disabled   Configured     
Sophos                    Antivirus            Disabled   Configured     
Symantec                  Antivirus            Disabled   Not Configured 
apk                       Processing           Disabled   Configured     
apk_verification          Processing           Disabled   Not Configured 
bamfdetect                Processing           Enabled    Configured     
cuckoo                    Processing           Enabled    Configured     
cuckoo_modified           Processing           Disabled   Configured     
cutthecrap                Processing           Disabled   Not Configured 
eml                       Processing           Enabled    Configured     
joe                       Processing           Disabled   Not Configured 
marcher_config            Processing           Disabled   Configured     
mem_yara                  Processing           Disabled   Not Configured 
office_macros             Processing           Enabled    Configured     
pdf                       Processing           Enabled    Configured     
rat_decoders              Processing           Enabled    Configured     
url_download              Processing           Enabled    Configured     
zip                       Processing           Enabled    Configured     
slack                     Reporting            Disabled   Not Configured 
Yeti                      Threat Intelligence  Disabled   Not Configured 
kvm                       Virtualization       Disabled   Configured     
virtualbox                Virtualization       Disabled   Configured

**Comment by rilian-la-te** [comment]
It will fixed by small patch:
```
diff --git a/fame/common/utils.py b/fame/common/utils.py
index b02265a..96628d7 100755
--- a/fame/common/utils.py
+++ b/fame/common/utils.py
@@ -25,13 +25,14 @@ def iterify(element):
 
 def u(string):
     try:
-        return unicode(string)
+        return unicode(string,'utf-8')
     except UnicodeDecodeError:
         try:
             return unicode(string, 'latin-1')
         except UnicodeDecodeError:
             return unicode(string, errors='replace')
-
+    except TypeError:
+        return string
 
 def get_class(module, klass):
     try:
```

**Comment by gaelmuller** [comment]
should now be fixed
