### ISSUE TITLE
Install From Scratch - Internal error submitting a sample

### ISSUE THREAD

**Issue by jomivz** [certsocietegenerale/fame#28]
### Description
When submitting a new sample, the webserver returned an Internal error.

### Steps to Reproduce
Install from scratch and submission of the sample [Shamoon from theZoo repo](https://github.com/ytisf/theZoo/tree/master/malwares/Binaries/Shamoon/Shamoon.zip)

#### Expected behavior
[How are you expecting the application to behave?]

#### Actual behavior

![capture du 2017-08-21 18-40-14](https://user-images.githubusercontent.com/22774233/29527437-6844957a-8688-11e7-9056-05702d43e788.png)
![capture du 2017-08-21 18-40-29](https://user-images.githubusercontent.com/22774233/29527436-6840eab0-8688-11e7-9379-a71a7eaa69ae.png)

[20170821-fame-issue_on-submit.txt](https://github.com/certsocietegenerale/fame/files/1239338/20170821-fame-issue_on-submit.txt)

### Debug

[20170821-fame-issue_on-submit_troubleshoot.txt](https://github.com/certsocietegenerale/fame/files/1239352/20170821-fame-issue_on-submit_troubleshoot.txt)
``]

**Comment by gaelmuller** [comment]
Could you verify if your user (uid=1000) has sufficient rights to write to `/usr/share/fame/storage/` ?

`$ sudo -u '#1000' touch /usr/share/fame/storage/test.txt` should work

**Comment by jomivz** [comment]
My user has UID=1000. I fixed the issue like this:
- Creation of the directory `/usr/share/fame/storage` which was missing
- Change of the owner of my install directory by the user session instead of root
- Rebooting services 

Install directory before changes :
![capture du 2017-08-23 11-17-18](https://user-images.githubusercontent.com/22774233/29606112-bb4e02a6-87dc-11e7-80fd-330dc0057f1e.png)

Install directory after changes :
![capture du 2017-08-23 11-44-18](https://user-images.githubusercontent.com/22774233/29607243-2a17e582-87e0-11e7-86bc-8ab714f7143d.png)

Submission on success  :
![capture du 2017-08-23 11-43-35](https://user-images.githubusercontent.com/22774233/29607249-305ea02a-87e0-11e7-9577-b1a7e02507fd.png)

Thanks you for help!

**Comment by gaelmuller** [comment]
Perfect. Do not forget to enable some modules if you want anything to happen 😄
