### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by FafnerKeyZee** [certsocietegenerale/fame#3]
### Description
Got this error in configuration tab for AntiVirus

> python /home/USER/fame/fame/modules/community/antivirus/mail/install.py: error on 'fame':
> 
> Missing dependency: 7z

Looks like a requirement is need. (Running on fresh install of Ubuntu 16.04)

Please add this package for install:
p7zip-full

Best regards,

**Comment by gaelmuller** [comment]
This is actually the expected behavior, since p7zip-full is not a dependency for FAME. It is only needed if you want to enable some of the antivirus modules.

I get that this is not obvious and I updated the error message with installation instructions.
