### ISSUE TITLE
Delete submited samples

### ISSUE THREAD

**Issue by 007scorpio** [certsocietegenerale/fame#30]
Please how do i delete the samples already submitted and lastly a sample i have submited says #PENDING and it been long

**Comment by Heat-Miser** [comment]
Hello,

There is no real need for a delete functionality, you can leave your analysis even if they crash. But if you really want to delete them, you can use the shell.

`$>utils/run.sh utils/shell.py`

Get your analysis ID looking at the URL (http://myfame.domain.tld/analyses/FIXMEID)  then in the shell this should work:

```
from bson import ObjectId
from fame.core.file import File
from fame.core.analysis import Analysis

for a in Analysis.find(_id=ObjectId("FIXMEID")):
        for b in File.find(_id=a["file"]):
                b.delete()
        a.delete()
```
