### ISSUE TITLE
Ansible playbook for Setup automation

### ISSUE THREAD

**Issue by ninjatrench** [certsocietegenerale/fame#31]
### Description
I guess this project is being used by a lot of people and it would be nice to have one line installer script or ansible playbook to automate entire installation and configuration process.
Its kind of a feature request, but if it is in scope then I can write it and send a PR

**Comment by Heat-Miser** [comment]
Hello,

The installation process is not really hard from our point of view but if you want to improve it PR  is welcome :)

Thank you
