### ISSUE TITLE
How to compile fame on a Raspberry Pi 3B?

### ISSUE THREAD

**Issue by squadramunter** [certsocietegenerale/fame#32]
Hello I like to have fame on my Raspberry Pi 3B but since mongodb is only version v2.4.14 I can't rely on your documentation. Can you explain me how to correctly make the admin user and configuring the databases?

Greetings,

- SquadraMunter

**Comment by gaelmuller** [comment]
Hello, FAME is not compatible with mongo 2.x. You should find a way to install Mongo 3 on your system or you will have to change the system itself.
