### ISSUE TITLE
cannot running "utils/run.sh webserver.py"  and "utils/run.sh utils/install.py" 

### ISSUE THREAD

**Issue by agusdwimuladi** [certsocietegenerale/fame#40]
### Description
[can you help me, i cannot running "utils/run.sh webserver.py"  it says " WARNING: Do not use the development server in a production environment." and "utils/run.sh utils/install.py" it says "Could not connect to MongoDB database", thank you.]

### Steps to Reproduce
[Describe the steps to reproduce]

#### Expected behavior
[How are you expecting the application to behave?]

#### Actual behavior
[How is the application behaving? (include any stacktraces, logs, screenshots, etc.)]

### Debug
[Include the output of ``utils/run.sh utils/troubleshoot.py``]

**Comment by gaelmuller** [comment]
Closing in favor of https://github.com/certsocietegenerale/fame/issues/43
