### ISSUE TITLE
trouble update modules repository

### ISSUE THREAD

**Issue by agusdwimuladi** [certsocietegenerale/fame#42]
### Description
[excusme, i have trouble from update module repositori, and i have message : ValueError: Reserved characters such as ':' must be escaped according RFC 2396. An IPv6 address literal must be enclosed in '[' and ']' according to RFC 2732.

can you help me, thankyou.]

### Steps to Reproduce
[Describe the steps to reproduce]

#### Expected behavior
[How are you expecting the application to behave?]

#### Actual behavior
[How is the application behaving? (include any stacktraces, logs, screenshots, etc.)]

### Debug
[Include the output of ``utils/run.sh utils/troubleshoot.py``]

**Comment by gaelmuller** [comment]
Closing in favor of https://github.com/certsocietegenerale/fame/issues/43
