### ISSUE TITLE
problem in the menu Analysis Details.

### ISSUE THREAD

**Issue by agusdwimuladi** [certsocietegenerale/fame#43]
### Description
[problem in the menu Analysis Details, should there are some menus, for example execution path, observables, extracttions, detail results, and logs and while my menu is only there file details, execution path, logs.]

### Steps to Reproduce
[Describe the steps to reproduce]

#### Expected behavior
[How are you expecting the application to behave?]

#### Actual behavior
[How is the application behaving? (include any stacktraces, logs, screenshots, etc.)]

### Debug
[Include the output of ``utils/run.sh utils/troubleshoot.py``]

**Comment by gaelmuller** [comment]
The items in the "Analysis Details" are dynamic, so they will only appear if they have content. When your analysis modules were not successful, it is normal for certain items not to appear.

Please refer to the documentation (especially the guides) at https://fame.readthedocs.io/en/latest/ for information on how to use FAME.
