### ISSUE TITLE
problem fame

### ISSUE THREAD

**Issue by agusdwimuladi** [certsocietegenerale/fame#44]
### Description
[when I managed to access the fame, I got into trouble with the detail analysis menu, where when I tried to do the analysis I only get some menu just like: file details, execution path, logs and dimenu path there is still some constraint, when I read in fame documentation there some menu options such as: execution path, observables, extracttions, detailed results, and logs.
roughly for that problem how is the solution?
Your help is very much needed, thank you.]

### Steps to Reproduce
[Describe the steps to reproduce]

#### Expected behavior
[How are you expecting the application to behave?]

#### Actual behavior
[How is the application behaving? (include any stacktraces, logs, screenshots, etc.)]

### Debug
[Include the output of ``utils/run.sh utils/troubleshoot.py``]

**Comment by gaelmuller** [comment]
Closing in favor of https://github.com/certsocietegenerale/fame/issues/43
