### ISSUE TITLE
fame menu issues

### ISSUE THREAD

**Issue by agusdwimuladi321** [certsocietegenerale/fame#45]
### Description
[when I managed to access the fame, I got into trouble with the detail analysis menu, where when I tried to do the analysis I only get some menu just like: file details, execution path, logs and dimenu path there is still some constraint, when I read in fame documentation there some menu options such as: execution path, observables, extracttions, detailed results, and logs.
roughly for that problem how is the solution? thank you very much.]

### Steps to Reproduce
[I hope fame that I install can run according to the documentation and can run well]

#### Expected behavior
[I only get some menu just like: file details, execution path, logs ]

#### Actual behavior
[How is the application behaving? (include any stacktraces, logs, screenshots, etc.)]

### Debug
[Include the output of ``utils/run.sh utils/troubleshoot.py``]

**Comment by gaelmuller** [comment]
Closing in favor of https://github.com/certsocietegenerale/fame/issues/43
