### ISSUE TITLE
fame installation is not running 

### ISSUE THREAD

**Issue by agusdwimuladi** [certsocietegenerale/fame#46]
### Description
[when running the script : "utils/run.sh utils/install.py" i have message 127.0.0.1:27017: [Errno 111] Connection refused
]

### Steps to Reproduce
[Describe the steps to reproduce]

#### Expected behavior
[can do installation fame]

#### Actual behavior
[How is the application behaving? (include any stacktraces, logs, screenshots, etc.)]

### Debug
[root@bismillah-VirtualBox:/home/bismillah/fame# utils/run.sh utils/troubleshoot.py
[+] Using existing virtualenv.

########## VERSION ##########

OS: Linux-4.10.0-28-generic-x86_64-with-Ubuntu-16.04-xenial
Python: 2.7.12

########## DEPENDENCIES ###########

alabaster==0.7.11
amqp==2.3.2
Babel==2.6.0
billiard==3.5.0.4
celery==4.1.1
certifi==2018.4.16
chardet==3.0.4
click==6.7
docutils==0.14
Flask==1.0.2
Flask-Classy==0.6.10
Flask-Login==0.3.2
Flask-Negotiation==0.1.9
flask-paginate==0.5.1
gitdb2==2.0.4
GitPython==2.1.11
idna==2.6
imagesize==1.0.0
itsdangerous==0.24
Jinja2==2.10
kombu==4.2.1
LEPL==5.1.3
markdown2==2.3.5
MarkupSafe==1.0
packaging==17.1
Pygments==2.2.0
pymongo==3.6.1
pyparsing==2.2.0
python-magic==0.4.15
pytz==2018.5
requests==2.18.4
rfc6266==0.0.4
six==1.11.0
smmap2==2.0.4
snowballstemmer==1.2.1
Sphinx==1.7.6
sphinx-rtd-theme==0.3.1
sphinxcontrib-httpdomain==1.6.1
sphinxcontrib-websupport==1.1.0
typing==3.6.4
urllib3==1.22
vine==1.1.4
Werkzeug==0.14.1
zxcvbn==1.0

########## MongoDB ##########

Could not connect to MongoDB: localhost:27017: [Errno 111] Connection refused
]

**Comment by Heat-Miser** [comment]
Hello,

according to the error message, Fame is not able to connect to the mongo DB. 

Please check that your Mongod is running. Check also that the credentials you provided in fame.conf are correct and works on this instance.

**Comment by agusdwimuladi** [comment]
halo,
I've tried running mongodb using commands "service mongod start" and I have checked mongodb at /var/log/mongodb/mongod.log and I checked in the line reading there is "[initandlisten] waiting for connections on port 27017" and when I try to run "utils / run.sh utils / install.py" still i have message 127.0.0.1:27017: [Errno 111] Connection refused. 
if for fame.conf it look for it where, thank you very much.

**Comment by udgover** [comment]
Can you comment the following line in install.py : 

https://github.com/certsocietegenerale/fame/blob/master/utils/install.py#L64

It seems with newer mongodb version, this call is no longer possible without being authenticated if previously enabled in mongodb.conf.

**Comment by agusdwimuladi** [comment]
thank you very much, this can work.

**Comment by agusdwimuladi** [comment]
but i have trouble after entering data, example : 
root@ayo-VirtualBox:/home/ayo/fame# utils/run.sh utils/install.py
[+] Using existing virtualenv.

[+] Installing requirements ...
[?] MongoDB host [localhost]: 127.0.0.1:27017
[?] MongoDB port [27017]: 27017
[?] MongoDB database [fame]: fame
[?] MongoDB username: fame
[?] MongoDB password: 654321

/!\ Could not connect to MongoDB (invalid credentials).
root@ayo-VirtualBox:/home/ayo/fame# utils/run.sh utils/install.py
[+] Using existing virtualenv.

[+] Installing requirements ...
[?] MongoDB host [localhost]: 127.0.0.1:27017
[?] MongoDB port [27017]: 27017
[?] MongoDB database [fame]: admin
[?] MongoDB username: admin
[?] MongoDB password: 123321

/!\ Could not connect to MongoDB (invalid credentials).

**Comment by Heat-Miser** [comment]
I guess you're using wrong credentials ? You must have create an account before. Use it.
