### ISSUE TITLE
Suggested enhancement for JSON parsing

### ISSUE THREAD

**Issue by smclinden** [certsocietegenerale/fame#59]
The following describes a method for backending ijson with a C language based parser to replace the pure Python based parser. I have applied it to a fork of the Cuckoo module and it appears to be significanty faster.

http://lpetr.org/blog/archives/faster-json-parsing-python-ijson

**Comment by Augustin-FL** [comment]
Hi,

Thank you for the suggestion, however FAME doesn't need to parse JSON very fast.
