### ISSUE TITLE
Wating for pending tasks very long time?

### ISSUE THREAD

**Issue by conghtse05773** [certsocietegenerale/fame#64]
### Description
I has misconfigured cuckoo (wrong cuckoo api endpoint) but had submitted some tasks to analysis. 
The I fixed and pressed reload configuration =)) it doesn't work because it have to wait for that tasks to complete
Because wait_timeout is 5400 = 90 minutes so I have to wait for that time ?
Why doesn't it have a cancel button, it's useful in some situations as me

![image](https://user-images.githubusercontent.com/26521562/53486084-5a9bd180-3aba-11e9-8765-b9063c8e2a9d.png)

**Comment by gaelmuller** [comment]
Hello,

An issue for a cancel button already exists here https://github.com/certsocietegenerale/fame/issues/7

That said, it looks like something different might be happening here. Your analyses seem to be `pending`. Do you have a worker running ?
