### ISSUE TITLE
Cannot run webserver interface

### ISSUE THREAD

**Issue by conghtse05773** [certsocietegenerale/fame#65]
### Description
![image](https://user-images.githubusercontent.com/26521562/55041878-b463cd00-5061-11e9-9360-10efc1927da4.png)

### Steps to Reproduce
sudo rm -r fame
clone from github
do installing
sudo utils/run.sh webserver

#### Expected behavior
No errors will happen

#### Actual behavior
[How is the application behaving? (include any stacktraces, logs, screenshots, etc.)]

### Debug
[+] Using existing virtualenv.

########## VERSION ##########

OS: Linux-4.15.0-46-generic-x86_64-with-Ubuntu-18.04-bionic
Python: 2.7.15rc1

########## DEPENDENCIES ###########

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
alabaster==0.7.12
amqp==2.4.2
Babel==2.6.0
billiard==3.5.0.5
celery==4.1.1
certifi==2019.3.9
chardet==3.0.4
Click==7.0
docutils==0.14
Flask==1.0.2
Flask-Classy==0.6.10
Flask-Login==0.3.2
Flask-Negotiation==0.1.9
flask-paginate==0.5.2
gitdb2==2.0.5
GitPython==2.1.11
idna==2.6
imagesize==1.1.0
itsdangerous==1.1.0
Jinja2==2.10
kombu==4.4.0
LEPL==5.1.3
markdown2==2.3.7
MarkupSafe==1.1.1
packaging==19.0
pkg-resources==0.0.0
Pygments==2.3.1
pymongo==3.6.1
pyparsing==2.3.1
python-magic==0.4.15
pytz==2018.9
requests==2.18.4
rfc6266==0.0.4
six==1.12.0
smmap2==2.0.5
snowballstemmer==1.2.1
Sphinx==1.7.9
sphinx-rtd-theme==0.3.1
sphinxcontrib-httpdomain==1.6.1
sphinxcontrib-websupport==1.1.0
typing==3.6.6
urllib3==1.22
vine==1.3.0
Werkzeug==0.15.1
zxcvbn==1.0

########## MongoDB ##########

Version: 4.0.6
Authorization check: True

########## Configuration ##########

types: True
virustotal: False

Modules:

**Comment by certsocietegenerale** [comment]
Hello,

We encounter this issue with the most recent version of Werkzeug. We are going to commit a working patch.
