### ISSUE TITLE
self parameter is missing

### ISSUE THREAD

**Issue by 0bscurec0de** [certsocietegenerale/fame#71]
Guys, I was just reviewing the "FiletypeModule" and I saw that you missed the self parameter for the recognize method, once it is added it works perfectly fine.

https://github.com/certsocietegenerale/fame/blob/28a80ece07d868cb2faf4279d8175bb70246df85/fame/core/module.py#L972

**Comment by gaelmuller** [comment]
Thank you for reporting this, I fixed it.
