### ISSUE TITLE
Connecting with cuckoo

### ISSUE THREAD

**Issue by mateuszbanaszewski18** [certsocietegenerale/fame#73]
### Description
I am trying to run analysis on Fame using cuckoo module. Every analysis ends up the same, Fame sends warning :
warning: could not find execution path to "cuckoo" (cancelled)
Cuckoo works flawlessly, it analyzes every file I give him. I am stuck with this issue for a long time, please help

### Steps to Reproduce
I have installed cuckoo using this guide:
https://gist.github.com/braimee/bf570a62f53f71bad1906c6e072ce993
I have installed Fame using official documentation:
https://fame.readthedocs.io/en/latest/installation.html#install-fame
Both cuckoo and Fame runs on the same machine (Ubuntu 18.04 bionic). I have opened ports regarding cuckoo, cuckoo api, fame web and fame worker. I did not configure api, I dont know how to do it. Fame web works on development, not production. I am not using uwsgi nor nginx. I am not using cuckoo-modified, only cuckoo. Cuckoo module is enabled in configuration and set to proper urls/ports. 

Fame directory:
/fame

Cuckoo directory (CWD):
/home/cuckoo/.cuckoo

#### Expected behavior
I expect Fame to give me full analysis log from cuckoo module.

#### Actual behavior

Instead analyzing through cuckoo module I am receiving this log:
2019-10-22 00:06: debug: Trying to queue module 'cuckoo'
2019-10-22 00:06: warning: could not find execution path to "cuckoo" (cancelled)
And cuckoo remains unruffled.

### Debug

cuckoo@ubuntu:/fame$ sudo /fame/utils/run.sh utils/troubleshoot.py
[+] Using existing virtualenv.

########## VERSION ##########

OS: Linux-5.0.0-31-generic-x86_64-with-Ubuntu-18.04-bionic
Python: 2.7.15+

########## DEPENDENCIES ###########

Traceback (most recent call last):
  File "utils/troubleshoot.py", line 87, in <module>
    main()
  File "utils/troubleshoot.py", line 82, in main
    dependencies()
  File "utils/troubleshoot.py", line 29, in dependencies
    pipmain(['freeze'])
TypeError: 'module' object is not callable

**Comment by gaelmuller** [comment]
Hello. It is probably due to the type of the file. Could you take a screenshot of the first table of the FAME analysis ? The one with the hashes and the type.

**Comment by mateuszbanaszewski18** [comment]
I added eml file to types, but now Im getting different error, please see the screenshot below:

![Screenshot (8)](https://user-images.githubusercontent.com/48993092/67267498-b59f9000-f4b2-11e9-85df-9f2f26f1043a.png)

**Comment by gaelmuller** [comment]
Could you tell us what version of Cuckoo Sandbox you are using ?

**Comment by mateuszbanaszewski18** [comment]
The version is 2.0.7

**Comment by gaelmuller** [comment]
Closing in favor of https://github.com/certsocietegenerale/fame_modules/issues/29
