### ISSUE TITLE
hit issue when running webserver.py

### ISSUE THREAD

**Issue by jozzytan** [certsocietegenerale/fame#74]
### Description
hit import error when running webserver and worker

### Steps to Reproduce
utils/run.sh webserver.py
traceback (most recent call last):
  file "webserver.py", line 4, in <module>
    import jinja2
importerror: no module named jinja2
utils/run.sh worker.py
[+] using existing virtualenv
traceback (most recent call last):
  file "webserver.py", line 4, in <module>
      import requests
importerror: no module named requests

#### Expected behavior
[How are you expecting the application to behave?]

#### Actual behavior
[How is the application behaving? (include any stacktraces, logs, screenshots, etc.)]

### Debug
[Include the output of ``utils/run.sh utils/troubleshoot.py``]

**Comment by gaelmuller** [comment]
Did you follow installation instructions ? It seem you do not have essential python packages in your virtualenv.

**Comment by jozzytan** [comment]
yes, python fault :) thanks
