### ISSUE TITLE
temp directory cleanup?

### ISSUE THREAD

**Issue by xme** [certsocietegenerale/fame#77]
My $INSTALLDIR/temp directory is very big. Is there a way to clean it in a safe way?
It contains files from approx 1 month of analyzis. So, I presume there is an automatic cleanup ongoing. Can we finetune this to keep the directory size under control?

**Comment by gaelmuller** [comment]
The current cleanup process is not ideal: it keeps only files that were modified during the last 7 days, but the catch is that it only runs when the worker is starting.

So a safe way to clean it would be to restart the worker.

Do not hesitate to reopen if needed.

**Comment by xme** [comment]
Indeed, it worked! Tx & Merry Christmas!
