### ISSUE TITLE
Webserver.py start werkzeug error cannot import name url_encode

### ISSUE THREAD

**Issue by frantz2501** [certsocietegenerale/fame#83]
### Description
[Please provide a description of the issue encountered]
Error at start up
`From werkzeug Cannot import name url_encode`

### Steps to Reproduce
[Describe the steps to reproduce]
`utils/run.sh webserver.py`

#### Expected behavior
[How are you expecting the application to behave?]
Running
#### Actual behavior
[How is the application behaving? (include any stacktraces, logs, screenshots, etc.)]
Error
### Debug
[Include the output of ``utils/run.sh utils/troubleshoot.py``]

In webserver.py, replace:
`from werkzeug import url_encode`
by
`from werkzeug.urls import url_encode`

https://werkzeug.palletsprojects.com/en/0.16.x/urls/

**Comment by stefanbulof** [comment]
in webserver.py
replace line 10
"from werkzeug import url_encode"
with 
"from werkzeug.urls import url_encode"

**Comment by Heat-Miser** [comment]
Thanks

this is due to a change in the latest version of Werkzeug.

I'm gonna fix it !

**Comment by Heat-Miser** [comment]
fixed now
