### ISSUE TITLE
Can't unzip protected archive?

### ISSUE THREAD

**Issue by xme** [certsocietegenerale/fame#84]
### Description

When I submit a zip archive protected with a password ('infected'), it can't be unzipped. Say "password not know"

### Steps to Reproduce

Upload a protected zip file

#### Expected behavior

Extract the content

#### Actual behavior

Can't uncompress the archive using the provided list of passwords

### Debug

I added some debugging code in the zip.py module. I see that the module tried all provided passwords but no luck to decrypt. The valid password is the 1st one of the list ("infected").

**Comment by xme** [comment]
Apparently, the module splits the provided passwords with '\n' but my passwords contained an extra character... maybe '\r' ?
I fixed the problem by using this:

`pwd=password.rstrip()`

Strange...

**Comment by Heat-Miser** [comment]
Hello

interesting, I'm gonna add a rstrip the password candidates, it's cheap and efficient.

Thanks

**Comment by Heat-Miser** [comment]
Fixed here

https://github.com/certsocietegenerale/fame_modules/commit/811a8e428b3e55c723501ba79c6ff9d274de4c27

Thanks
