### ISSUE TITLE
Can't run module "cutthecrap"

### ISSUE THREAD

**Issue by Serdet-git** [certsocietegenerale/fame#85]
### Description
When running "cutthecrap" kvm indicate that dependency "libvirt" is missing, but it installed and work

#### Actual behavior
1) error: cutthecrap: kvm: Missing dependency: libvirt
![image](https://user-images.githubusercontent.com/63682071/79464669-0a0b6e80-8003-11ea-9e83-42f58cdb89bc.png)
2) Libvirt is already running
![image](https://user-images.githubusercontent.com/63682071/79464832-43dc7500-8003-11ea-82e1-b8fd0609c2f8.png)

**Comment by gaelmuller** [comment]
This is actually a Python dependency issue. Could you run `env/bin/pip install libvirt-python` inside FAME's directory and try again ?

**Comment by Serdet-git** [comment]
This method does not work. Libvirt-python requires python version 3.

**Comment by gaelmuller** [comment]
`libvirt-python` dropped support for Python 2 recently. You should try installing one of the latest compatible version with `env/bin/pip install libvirt-python==5.10.0` until we port FAME to Python 3.

**Comment by Serdet-git** [comment]
After installing libvirt-python, the system warned about the absence of winappdbg and agent.py informed that a Post request was received. I forgot to install it on the VM, so I immediately installed winappdbg and pypiwin32. After successful installation, the problem with libvirt appeared again.

**Comment by gaelmuller** [comment]
There was no need to use `sudo` since you were installing it inside a virtualenv. Could you run `env/bin/pip freeze` and make sure `libvirt-python` is listed ?

**Comment by gaelmuller** [comment]
This should be fixed with Python 3 support and the new cutthecrap implementation
