### ISSUE TITLE
Modules Missing dependencies 

### ISSUE THREAD

**Issue by jcroy** [certsocietegenerale/fame#88]
So I'm trying to get fame working on Ubuntu 16.04+18.04 and have noticed that out of the box following the documentation, several modules don't install properly.  Peepdf, urlpreview, and exiftool all failed following the instructions.   

I copy and paste the instructions on the documentation part of fame, as well as installed docker and fixed group issue.  

Peepdf and other tools should work out of the box I am assuming based off of the module behavior.  

Peepdf, has an issue with Pillow, Exiftool has a 404 with docker I believe, and urlpreview has an npm issue? I can get further details when I restart...I forgot to save the snapshot.  I was hoping I this post could highlight anything I am missing or did incorrectly.

**Comment by gaelmuller** [comment]
This should now be fixed
