### ISSUE TITLE
TemplateNotFound: analysis/index.html

### ISSUE THREAD

**Issue by 007scorpio** [certsocietegenerale/fame#9]
After loging into fame.. i get the error that : TemplateNotFound: analysis/index.html

**Comment by gaelmuller** [comment]
This is super weird.

Could you please provide the output of the following command, from the directory containing FAME's code:

```
$ find web
```

**Comment by 007scorpio** [comment]
web
web/views
web/views/mixins.py
web/views/helpers.pyc
web/views/constants.pyc
web/views/analyses.py
web/views/analyses.pyc
web/views/users.pyc
web/views/modules.pyc
web/views/search.pyc
web/views/negotiation.py
web/views/constants.py
web/views/__init__.pyc
web/views/negotiation.pyc
web/views/files.pyc
web/views/search.py
web/views/__init__.py
web/views/configs.py
web/views/configs.pyc
web/views/modules.py
web/views/helpers.py
web/views/mixins.pyc
web/views/files.py
web/views/users.py
web/__init__.pyc
web/__init__.py
web/static
web/static/js
web/static/js/bootstrap-notify.min.js
web/static/js/bootstrap.min.js
web/static/js/fame.js
web/static/js/tagsinput.js
web/static/js/checkbox.js
web/static/js/bootstrap.js
web/static/js/typeahead.bundle.min.js
web/static/js/template.js
web/static/js/npm.js
web/static/js/highlight.min.js
web/static/js/fileinput.min.js
web/static/js/modules-typeahead.js
web/static/js/jquery-1.11.3.min.js
web/static/js/fame-file.js
web/static/js/handlebars.min.js
web/static/fonts
web/static/fonts/Pe-icon-7-stroke.woff
web/static/fonts/Pe-icon-7-stroke.eot
web/static/fonts/fontawesome-webfont.svg
web/static/fonts/fontawesome-webfont.woff2
web/static/fonts/glyphicons-halflings-regular.ttf
web/static/fonts/Pe-icon-7-stroke.svg
web/static/fonts/glyphicons-halflings-regular.woff2
web/static/fonts/Pe-icon-7-stroke.ttf
web/static/fonts/glyphicons-halflings-regular.eot
web/static/fonts/fontawesome-webfont.ttf
web/static/fonts/fontawesome-webfont.woff
web/static/fonts/fontawesome-webfont.eot
web/static/fonts/glyphicons-halflings-regular.woff
web/static/fonts/glyphicons-halflings-regular.svg
web/static/fonts/FontAwesome.otf
web/static/favicon.png
web/static/img
web/static/img/computer_code.jpg
web/static/img/sidebar.jpg
web/static/img/mask.png
web/static/img/avatars
web/static/img/avatars/58da87c8fb99aa13c2f5c47d.png
web/static/img/avatars/default.png
web/static/css
web/static/css/bootstrap.css
web/static/css/fileinput.min.css
web/static/css/bootstrap-theme.css
web/static/css/bootstrap-theme.min.css
web/static/css/template.css
web/static/css/bootstrap.css.map
web/static/css/pe-icon-7-stroke.css
web/static/css/font-awesome.min.css
web/static/css/animate.css
web/static/css/bootstrap-theme.css.map
web/static/css/bootstrap.min.css
web/static/css/fame.css
web/static/css/highlight.railscasts.min.css
web/auth
web/auth/user_password
web/auth/user_password/user_management.py
web/auth/user_password/views.pyc
web/auth/user_password/views.py
web/auth/user_password/__init__.pyc
web/auth/user_password/__init__.py
web/auth/user_password/templates
web/auth/user_password/templates/password_reset_form.html
web/auth/user_password/templates/mail_user_creation.html
web/auth/user_password/templates/mail_reset_password.html
web/auth/user_password/templates/auth_profile.html
web/auth/user_password/templates/login.html
web/auth/user_password/templates/base_unauthenticated.html
web/auth/user_password/templates/password_reset.html
web/auth/user_password/user_management.pyc
web/auth/saml
web/auth/saml/user_management.py
web/auth/saml/views.py
web/auth/saml/__init__.py
web/auth/saml/config
web/auth/saml/config/__init__.py
web/auth/saml/config/.gitignore
web/auth/saml/config/custom_mappings.py.sample
web/auth/saml/config/settings.json.sample
web/auth/__init__.pyc
web/auth/__init__.py
web/templates
web/templates/configs
web/templates/configs/single_block.html
web/templates/configs/target_attributes.html
web/templates/configs/botnet_list.html
web/templates/configs/index.html
web/templates/configs/show.html
web/templates/base.html
web/templates/users
web/templates/users/_form.html
web/templates/users/new.html
web/templates/users/index.html
web/templates/users/profile.html
web/templates/search.html
web/templates/analyses
web/templates/analyses/details.html
web/templates/analyses/new.html
web/templates/analyses/index.html
web/templates/analyses/show.html
web/templates/analyses/_options.html
web/templates/analyses/list.html
web/templates/files
web/templates/files/details.html
web/templates/files/index.html
web/templates/files/show.html
web/templates/files/list.html
web/templates/modules
web/templates/modules/module_configuration.html
web/templates/modules/templates.html
web/templates/modules/configuration.html
web/templates/modules/index.html
web/templates/modules/repository_new.html
web/templates/modules/_configuration.html

**Comment by gaelmuller** [comment]
Did you change some code ?

The line 81 of web/views/analyses.py should read (analys**es**, not analysis):

```
return render(analyses, 'analyses/index.html', ctx={'data': analyses, 'pagination': pagination})
```

**Comment by 007scorpio** [comment]
Sorry dude line 81: return render(analyses, 'analyses/index.html', ctx={'data': analyses, 'pagination': pagination}) i the same in my code. it throwing the exception jinja2.exeception.TemplateNotFound. (TemplateNotFound: analyses/index.html 

Please pythong is not my mother tongue so please help me. I need Your program badly. Thanks

**Comment by gaelmuller** [comment]
You have to make sure you are launching the webserver from FAME's root directory:

```
$ utils/run.sh webserver.py
```

**NOT**

```
$ fame/utils/run.sh fame/webserver.py
```

**Comment by 007scorpio** [comment]
yes man thanks it working perfectly now... thanks for the Good work done...

**Comment by 007scorpio** [comment]
Hi Please how to I delete an analysis? And after initiating an analysis it says pending and takes a longer time…. What could be wrong or is 
It something I have not done right.. Thanks

**Comment by gaelmuller** [comment]
You cannot delete an analysis at the moment. If your analysis remains in 'pending' state, it means that you have no associated worker launched and ready to access new tasks.
