### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by fenderstrato666** [certsocietegenerale/fame#97]
### Description
After fresh installation, first login. Password forgotten. How to reset.

**Comment by lightningwaterbright** [comment]
have you tried reinstalling fame?

**Comment by Augustin-FL** [comment]
Hello,

In such situation, you should click the "Reset password" link on the login page.
If this link is not working (SMTP server not yet configured?) then I would indeed recommend to reinstall.

If re-installing is not an option for you, you can reset an account programmatically in few commands :
```
./utils/run.sh utils/shell.py 
[+] Using existing virtualenv.

Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from fame.core.user import User
>>> from web.auth.user_password.user_management import change_password
>>> change_password(User.get(name="Admin"), "newpassword")
```

I will close this issue for now. Feel free to re-open it if needed !
